package com.gas.Securitycheck.utils;

/**
 * Created by Administrator on 2016/10/11 0011.
 */
public class dataAppUtil {

    // 这个是隐患项的数据
    public static String HiddenDangerItemData="{    \"data\": [        {            \"Photograph\": \"保存路径\",            \"content\": \"①燃气软管已经老化、龟裂或不是专用耐油橡胶管，有图片。\",            \"edit\": \"已经编辑\",            \"isTrue\": \"true\"        },        {            \"Photograph\": \"保存路径\",            \"content\": \"②软管两端没有固定牢固，有图片。\",            \"edit\": \"已经编辑\",            \"isTrue\": \"true\"        },        {            \"Photograph\": \"保存路径\",            \"content\": \"③软管长度超过2米，有图片\",            \"edit\": \"已经编辑\",            \"isTrue\": \"false\"        },        {            \"Photograph\": \"保存路径\",            \"content\": \"④软管穿越门、窗及墙壁，有图片。\",            \"edit\": \"已经编辑\",            \"isTrue\": \"false\"        },        {            \"Photograph\": \"保存路径\",            \"content\": \"⑪燃气管道、设施上方有搭接电线、铁丝网、绳索等附着物，有图片。\",            \"edit\": \"已经编辑\",            \"isTrue\": \"true\"        },        {            \"Photograph\": \"保存路径\",            \"content\": \"③软管长度超过2米，有图片\",            \"edit\": \"已经编辑\",            \"isTrue\": \"false\"        },        {            \"Photograph\": \"保存路径\",            \"content\": \"④软管穿越门、窗及墙壁，需整改。\",            \"edit\": \"已经编辑\",            \"isTrue\": \"false\"        }    ],    \"limit\": 0,    \"msg\": \"查询成功！\",    \"start\": 0,    \"success\": true,    \"total\": 2}";



    // 这个是安检项的数据
    public static String SecurityItemData="{    \"data\": [        {            \"Photograph\": \"保存路径\",            \"content\": \"①燃气软管已经老化、龟裂或不是专用耐油橡胶管，需整改。\",            \"edit\": \"已经编辑\",            \"isTrue\": \"true\"        },        {            \"Photograph\": \"保存路径\",            \"content\": \"②软管两端没有固定牢固，需整改。\",            \"edit\": \"已经编辑\",            \"isTrue\": \"true\"        },        {            \"Photograph\": \"保存路径\",            \"content\": \"③软管长度超过2米，需整改\",            \"edit\": \"已经编辑\",            \"isTrue\": \"false\"        },        {            \"Photograph\": \"保存路径\",            \"content\": \"④软管穿越门、窗及墙壁，需整改。\",            \"edit\": \"已经编辑\",            \"isTrue\": \"false\"        },        {            \"Photograph\": \"保存路径\",            \"content\": \"⑦灶前胶管阀门为：1、单出口阀门（球阀、旋塞式）；2、双出口阀门（旋塞式球阀，其它胶管阀门需整改。\",            \"edit\": \"已经编辑\",            \"isTrue\": \"true\"        },        {            \"Photograph\": \"保存路径\",            \"content\": \"⑪燃气管道、设施上方有搭接电线、铁丝网、绳索等附着物，需整改。\",            \"edit\": \"已经编辑\",            \"isTrue\": \"true\"        },        {            \"Photograph\": \"保存路径\",            \"content\": \"③软管长度超过2米，需整改\",            \"edit\": \"已经编辑\",            \"isTrue\": \"false\"        },        {            \"Photograph\": \"保存路径\",            \"content\": \"④软管穿越门、窗及墙壁，需整改。\",            \"edit\": \"已经编辑\",            \"isTrue\": \"false\"        },        {            \"Photograph\": \"保存路径\",            \"content\": \"①燃气软管已经老化、龟裂或不是专用耐油橡胶管，需整改。\",            \"edit\": \"已经编辑\",            \"isTrue\": \"true\"        },        {            \"Photograph\": \"保存路径\",            \"content\": \"②软管两端没有固定牢固，需整改。\",            \"edit\": \"已经编辑\",            \"isTrue\": \"true\"        },        {            \"Photograph\": \"保存路径\",            \"content\": \"③软管长度超过2米，需整改\",            \"edit\": \"已经编辑\",            \"isTrue\": \"false\"        },        {            \"Photograph\": \"保存路径\",            \"content\": \"④软管穿越门、窗及墙壁，需整改。\",            \"edit\": \"已经编辑\",            \"isTrue\": \"false\"        },        {            \"Photograph\": \"保存路径\",            \"content\": \"①燃气软管已经老化、龟裂或不是专用耐油橡胶管，需整改。\",            \"edit\": \"已经编辑\",            \"isTrue\": \"true\"        },        {            \"Photograph\": \"保存路径\",            \"content\": \"②软管两端没有固定牢固，需整改。\",            \"edit\": \"已经编辑\",            \"isTrue\": \"true\"        },        {            \"Photograph\": \"保存路径\",            \"content\": \"③软管长度超过2米，需整改\",            \"edit\": \"已经编辑\",            \"isTrue\": \"false\"        },        {            \"Photograph\": \"保存路径\",            \"content\": \"④软管穿越门、窗及墙壁，需整改。\",            \"edit\": \"已经编辑\",            \"isTrue\": \"false\"        }    ],    \"limit\": 0,    \"msg\": \"查询成功！\",    \"start\": 0,    \"success\": true,    \"total\": 2}";


    // 这个是任务列表的数据
    public static String TaskListData="{    \"data\": [        {            \"CompletionStatus\": \"20/100\",            \"SerialNumber\": \"01\",            \"name\": \"朝阳区甘露园1区\",            \"operation\": \"下载\",            \"state\": \"1次\",            \"time\": \"10/09\"        },        {            \"CompletionStatus\": \"20/100\",            \"SerialNumber\": \"02\",            \"name\": \"朝阳区甘露园2区\",            \"operation\": \"下载\",            \"state\": \"1次\",            \"time\": \"10/09\"        },        {            \"CompletionStatus\": \"20/100\",            \"SerialNumber\": \"03\",            \"name\": \"朝阳区甘露园3区\",            \"operation\": \"执行\",            \"state\": \"1次\",            \"time\": \"10/09\"        },        {            \"CompletionStatus\": \"20/100\",            \"SerialNumber\": \"04\",            \"name\": \"朝阳区甘露园4区\",            \"operation\": \"执行\",            \"state\": \"1次\",            \"time\": \"10/09\"        },        {            \"CompletionStatus\": \"20/100\",            \"SerialNumber\": \"05\",            \"name\": \"朝阳区甘露园5区\",            \"operation\": \"执行\",            \"state\": \"1次\",            \"time\": \"10/09\"        }    ],    \"limit\": 0,    \"msg\": \"查询成功！\",    \"start\": 0,    \"success\": true,    \"total\": 2}";



    // 这个是单个任务的数据
    public static String TaskInfo ="{    \"data\": [        {            \"address\": \"2号楼3单元503室\",            \"category\": \"租房户\",            \"operation\": \"入户\",            \"state\": \"低\"        },        {            \"address\": \"2号楼3单元502室\",            \"category\": \"普通户\",            \"operation\": \"查看\",            \"state\": \"低\"        },        {            \"address\": \"2号楼3单元502室\",            \"category\": \"重点户\",            \"operation\": \"查看\",            \"state\": \"低\"        },        {            \"address\": \"2号楼3单元502室\",            \"category\": \"租房户\",            \"operation\": \"查看\",            \"state\": \"低\"        },        {            \"address\": \"2号楼3单元502室\",            \"category\": \"租房户\",            \"operation\": \"入户\",            \"state\": \"低\"        },        {            \"address\": \"2号楼3单元502室\",            \"category\": \"重点户\",            \"operation\": \"入户\",            \"state\": \"低\"        },        {            \"address\": \"2号楼3单元502室\",            \"category\": \"普通户\",            \"operation\": \"入户\",            \"state\": \"低\"        },        {            \"address\": \"2号楼3单元502室\",            \"category\": \"租房户\",            \"operation\": \"入户\",            \"state\": \"低\"        },        {            \"address\": \"2号楼3单元502室\",            \"category\": \"租房户\",            \"operation\": \"入户\",            \"state\": \"低\"        },        {            \"address\": \"2号楼3单元502室\",            \"category\": \"租房户\",            \"operation\": \"入户\",            \"state\": \"低\"        },        {            \"address\": \"2号楼3单元502室\",            \"category\": \"租房户\",            \"operation\": \"入户\",            \"state\": \"低\"        },        {            \"address\": \"2号楼3单元502室\",            \"category\": \"租房户\",            \"operation\": \"入户\",            \"state\": \"低\"        },        {            \"address\": \"2号楼3单元502室\",            \"category\": \"租房户\",            \"operation\": \"入户\",            \"state\": \"低\"        },        {            \"address\": \"2号楼3单元502室\",            \"category\": \"租房户\",            \"operation\": \"入户\",            \"state\": \"低\"        },        {            \"address\": \"2号楼3单元501室\",            \"category\": \"租房户\",            \"operation\": \"入户\",            \"state\": \"低\"        }    ],    \"dataNumber\": 50,    \"limit\": 0,    \"msg\": \"查询成功！\",    \"start\": 0,    \"success\": true,    \"total\": 2}";
}
